<?php
	define('SAME_ZONE_AUTO', 1);
	define('DIFFERENT_ZONE_CROSS_MAPPING', 2);
	define('MANUAL_ZONE_MAPPING', 3);
	define('SAME_CITY_AUTO', 4);
	define('MANUAL_CITY_MAPPING',5);
	define('SAME_STATE_PROVINCE_AUTO',6);
	define('DIFFERENT_STATE_PROVINCE_CROSS_MAPPING',7);
	define('MANUAL_STATE_PROVINCE_MAPPING',8);
	define('SAME_COUNTRY_AUTO',9);
	define('DIFFERENT_COUNTRY_CROSS_MAPPING',10);
	define('MANUAL_COUNTRY_MAPPING',11);
?>